const loginView=document.querySelector('#login-view'),appView=document.querySelector('#app-view'),notice=document.querySelector('#notice');let catalog={};
const labels={gallery:'Images / gallery',videos:'Videos',documents:'PDF documents'};
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function showNotice(text,error=false){notice.textContent=text;notice.className=error?'notice error':'notice'}
function setLogin(show){loginView.hidden=!show;appView.hidden=show}
async function request(url,options){const response=await fetch(url,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Request failed');return data}
async function checkSession(){try{const data=await request('/api/me');if(data.authenticated){setLogin(false);await loadCatalog()}}catch(_){}};
async function loadCatalog(){catalog=await request('/api/media');renderCatalog();}
function renderCatalog(){const root=document.querySelector('#media-lists');root.innerHTML='';Object.entries(labels).forEach(([type,label])=>{const group=document.createElement('div');group.className='media-group';group.innerHTML=`<h3>${label}</h3>`;const items=catalog[type]||[];if(!items.length){group.innerHTML+='<p class="empty">No items yet.</p>'}items.forEach((item,index)=>{const row=document.createElement('div');row.className='media-row';const isVideo=type==='videos';const preview=type==='documents'?(item.cover||''):(item.src||'');row.innerHTML=`${preview?`<img class="media-thumb ${isVideo?'video':''}" src="/${esc(preview)}" alt="">`:'<div class="media-thumb"></div>'}<input data-field="title" data-type="${type}" data-index="${index}" value="${esc(item.title)}" aria-label="Title"><textarea data-field="description" data-type="${type}" data-index="${index}" rows="3" aria-label="Description">${esc(item.description)}</textarea><button class="remove" data-remove-type="${type}" data-remove-index="${index}" type="button">Hide</button>`;group.appendChild(row)}) ;root.appendChild(group)});}
document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();const error=document.querySelector('#login-error');error.textContent='';try{await request('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:document.querySelector('#password').value})});document.querySelector('#password').value='';setLogin(false);await loadCatalog()}catch(err){error.textContent=err.message}});
document.querySelector('#logout').addEventListener('click',async()=>{await request('/api/logout',{method:'POST'});setLogin(true)});
document.querySelector('#media-type').addEventListener('change',e=>{document.querySelector('#poster-field').hidden=e.target.value!=='videos';document.querySelector('#cover-field').hidden=e.target.value!=='documents';const file=document.querySelector('#media-file');file.accept=e.target.value==='videos'?'video/mp4,video/webm':e.target.value==='documents'?'.pdf':'image/*'});
document.querySelector('#upload-form').addEventListener('submit',async e=>{e.preventDefault();const status=document.querySelector('#upload-status');status.textContent='Uploading…';try{const data=await request('/api/media',{method:'POST',body:new FormData(e.target)});status.textContent='Published.';e.target.reset();document.querySelector('#poster-field').hidden=true;document.querySelector('#cover-field').hidden=true;await loadCatalog();showNotice(`Added “${data.item.title}”. The website will update after the repository deployment finishes.`)}catch(err){status.textContent=err.message}});
document.querySelector('#media-lists').addEventListener('click',e=>{const button=e.target.closest('[data-remove-type]');if(!button)return;const type=button.dataset.removeType,index=Number(button.dataset.removeIndex);catalog[type].splice(index,1);renderCatalog();showNotice('Item hidden locally. Click Save catalog changes to publish it.')});
document.querySelector('#save-catalog').addEventListener('click',async()=>{document.querySelectorAll('[data-field]').forEach(input=>{catalog[input.dataset.type][Number(input.dataset.index)][input.dataset.field]=input.value});try{for(const type of Object.keys(labels)){await request('/api/media',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({type,items:catalog[type]})})}showNotice('Catalog changes saved. The website will update after deployment.')}catch(err){showNotice(err.message,true)}});
checkSession();
